### ISSUE TITLE
Segmentation Faults

### ISSUE THREAD

**Issue by tabularasa7** [candeladd/2270_Project_AC#3]
Instructions on downloading and running program are very clear.  Program compiles and runs great.  Just a note, I used the test file that comes with the program to test it.

However, I found a couple of instances where user input causes segmentation faults if incorrect input is provided.  After creating the user database, here are some instance where errors are thrown or segmentation faults occur:
1.  This was admittedly found by a mistake on my part, however when selecting option 2 from the menu, if a letter is input for the chromosome, the program throws an 'invalid argument' error for stoi and performs an abort and core dump.
2. The reverse is also true for the genotype, where after selecting option 2 from the menu, if a number is entered into the program for the genotype, the program will output an 'Invalid Genotype' error and then seg faults.
3. While testing the print functions, the genotype print function will do the same as the genotype error in example 2 when a number is entered.  I believe this is because the printMatchingGeno function calls the same functions as the retrieveRSID function.
4. Lastly, when selecting 5 to print out chromosomal sections of data, if I enter a number for a chromosome that doesn't exist in the file, like the number 24, the program will then run through and print out a long section of the file before a seg fault occurs.

Overall, when used properly, the program works great for what seems to have been a very ambitious project.  I like the processing file print out statements that occur when the input file is being processed, as it does help the user be aware that the program is doing something, since the processing of the file seems to take a while.  Also, the other print out statements are formatted very nicely for easy reading.

**Comment by austinholler** [comment]
Thank you so much for the positive feedback! Glad to see you enjoyed the project; we thought it was pretty fun.

As for the errors, we left some issues in the program so there was something to do and it wasn't just all requests for adding stuff. I'm sure there are other errors that we don't know about, but the invalid inputs were errors we purposely left in to allow for "contributions".

Thanks again though for taking time to evaluate our project and hope you have a great summer!
