### ISSUE TITLE
For the most part, impressive.

### ISSUE THREAD

**Issue by sanoff** [candeladd/2270_Project_AC#5]
Hey guys, good work. For the most part this program works pretty well and serves its purpose. The functions and ReadMe are very thoughtful and well-written, and I felt like I knew what I was doing the entire time. The program runs fine except for in a few cases that I stumbled upon.
1. If an invalid character is input for integer arguments or otherwise, a Stoi argument error occurs and the program proceeds to seg fault. The best way to resolve this may be through a short checker function that checks the data type of the variable input before it attempts to proceeds to use it.
2. The method to print out the chromosome list. This is the only real "issue" I'd say the program has, and it's very similar in nature to the last one. If, for option 5, one fails to put down the name of a chromosome that is not in the list, the program will core dump after printing a long section of the chromosomes. A method to fix this might be to read the infile into an array that can be kept throughout the entirety of the time that the program is executed (this would also prevent the user from having to re-enter the file name). In doing this with a Hash table or otherwise, the program would first check to see that certain inputs exist before it runs them. This method could be used in other places such as the second menu option as well, to make sure that the user puts correct inputs before executing the method. 

However, other than these things, the program seems very competent, neat, and proficient. Well-named variables, well-described methods and pre/post conditions, and interesting concept to pursue in computer science. Good job, and good luck!

**Comment by austinholler** [comment]
Thank you so much for the positive feedback! Glad to see you enjoyed the project; we thought it was pretty fun.

As for the errors, we left some issues in the program so there was something to do and it wasn't just all requests for adding stuff. I'm sure there are other errors that we don't know about, but the invalid inputs were errors we purposely left in to allow for "contributions".

Thanks again though for taking time to evaluate our project and hope you have a great summer!
